### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [yug030/CSE15L_lab_report_1#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
   - ~~step 3 commands should be in backticks~~
   - ~~step 4 `scp` and `ls` command should be in backticks~~
   - ~~step 5 `ssh-keygen` should be in backticks~~
   - ~~same with commands in step 6~~
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - ~~not counting keystrokes~~
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by yug030** [comment]
Hello! I have made some changes to my lab1 report and I still want to get some clarifications.

1. Does code in backticks appears like this?
![image](https://user-images.githubusercontent.com/97643636/150881428-8be9a12c-a64d-47db-9a4c-3f06b00af4e9.png)

2. When we are required to "count keystrokes" are we supposed to show how we can save effort? For example, we need to press "Enter" 3 times when running 3 commands, but after introducing the new techniques we can compress 3 commands into a single command, saving 2 "Enter"s ?

**I was told there's only one regrade chance and we can ask for clarification here, but it was after I submitted the regrade request. If possible please regrade my lab later so that I can still make changes to my report after receiving valuable suggestions from you. Thank you!**

**Comment by nouryehia** [comment]
1. yes

`they look like this with single backticks (used for one liners/single commands)`

and 

```
they look like this with triple backticks (used for longer code snippets or to emphasize a smaller one)
```

2. I am fairly sure you can submit more than one regrade request, but I am not 100% sure. Go ahead and submit another one if possible. If you are unable to, please leave a comment on this issue and I'll go ahead and edit the grade on grade scope!

**Comment by yug030** [comment]
Thank you! My previous regrade request have not been accepted yet, so I think it is unnecessary for me to submit another one at this moment. Given the links are the same, I think my current edits will be displayed when the regrade request is accepted. Thank you for your response!

**Comment by yug030** [comment]
Hello! My regrade request still have not been approved, so I think even though there might be multiple regrade chances, they are going to restrict the chance to 1 time by finishing regrading after the ddl :(

If possible, could you review my lab report once more before Jan.28th because I really don't want to lose points in the very first lab. 

Here's the link:
https://yug030.github.io/CSE15L_lab_report_1/
 
Thank you for your time!

**Comment by nouryehia** [comment]
Apologies for the delay. I was doing regrade requests until Monday and then got extremely swamped with school. My plan was to get back to them tonight.
